export const EMPLOYEE_RANGES = [
  '1-10',
  '11-20',
  '21-50',
  '51-100',
  '101-250',
  '251-500',
  '501-1000',
  '1000+',
];

export const JOB_LOCATIONS = ['onsite', 'remotely', 'hybrid'];
export const WORKING_TIME = ['part-time', 'full-time'];
export const SENIORITY_LEVELS = [
  'Fresh',
  'Junior',
  'Mid-Level',
  'Senior',
  'Team-Lead',
  'CTO',
];

export const ALLOWED_ACTIONS = {
  // User actions
  USER_BANNED: 'USER_BANNED',
  USER_UNBANNED: 'USER_UNBANNED',
  USER_CREATED: 'USER_CREATED',
  USER_DELETED: 'USER_DELETED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  CONFIRM_EMAIL: 'CONFIRM_EMAIL',
  RESEND_OTP: 'RESEND_OTP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  GET_LOGGED_USER: 'GET_LOGGED_USER',
  GET_PUBLIC_PROFILE: 'GET_PUBLIC_PROFILE',
  UPLOAD_PROFILE_PICTURE: 'UPLOAD_PROFILE_PICTURE',
  DELETE_PROFILE_PICTURE: 'DELETE_PROFILE_PICTURE',
  UPLOAD_COVER_PICTURE: 'UPLOAD_COVER_PICTURE',
  DELETE_COVER_PICTURE: 'DELETE_COVER_PICTURE',
  RESTORE_USER: 'RESTORE_USER',

  // Auth actions
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',

  // Company actions
  COMPANY_CREATED: 'COMPANY_CREATED',
  COMPANY_UPDATED: 'COMPANY_UPDATED',
  COMPANY_DELETED: 'COMPANY_DELETED',
  COMPANY_APPROVED: 'COMPANY_APPROVED',
  COMPANY_BANNED: 'COMPANY_BANNED',
  COMPANY_UNBANNED: 'COMPANY_UNBANNED',
  VIEW_COMPANY: 'VIEW_COMPANY',
  UPLOAD_COMPANY_LOGO: 'UPLOAD_COMPANY_LOGO',
  DELETE_COMPANY_LOGO: 'DELETE_COMPANY_LOGO',
  UPLOAD_COMPANY_COVER: 'UPLOAD_COMPANY_COVER',
  DELETE_COMPANY_COVER: 'DELETE_COMPANY_COVER',
  ADD_HR_TO_COMPANY: 'ADD_HR_TO_COMPANY',
  REMOVE_HR_FROM_COMPANY: 'REMOVE_HR_FROM_COMPANY',

  // Job actions
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  JOB_DELETED: 'JOB_DELETED',
  GET_JOBS: 'GET_JOBS',
  GET_JOB: 'GET_JOB',

  // Application actions
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  GET_APPLICATIONS: 'GET_APPLICATIONS',
  APPLICATIONS_EXPORTED: 'APPLICATIONS_EXPORTED',
};
export const ALLOWED_ACTIONS = [
  // User actions
  'USER_BANNED',
  'USER_UNBANNED',
  'USER_CREATED',
  'USER_DELETED',
  'PROFILE_UPDATED',
  'PASSWORD_RESET',
  'PASSWORD_CHANGED',

  // Auth actions
  'LOGIN',
  'LOGOUT',
  'TOKEN_REFRESHED',

  // Company actions
  'COMPANY_CREATED',
  'COMPANY_UPDATED',
  'COMPANY_DELETED',
  'COMPANY_APPROVED',
  'COMPANY_BANNED',
  'COMPANY_UNBANNED',
  'VIEW_COMPANY',

  // Job actions
  'JOB_CREATED',
  'JOB_UPDATED',
  'JOB_DELETED',

  // Application actions
  'APPLICATION_SUBMITTED',
  'APPLICATION_STATUS_CHANGED',
];

export const ALLOWED_SORT_FIELDS = ['createdAt', 'action'];
export const ALLOWED_SORT_ORDERS = ['asc', 'desc'];
